---
# Packages
default_system_upgrade_all_packages: false

# Hosts file
default_system_hosts_file_create: true
default_system_hosts_group: "{{ groups['all'] }}"
default_system_hosts_file: /etc/hosts
default_system_hosts_file_disable_entries: []

# Firewall
default_system_firewall_disable: false

# Selinux
default_system_selinux_disable: false

# Extend OS LVM
default_system_extend_os_lvm: false
default_system_extend_os_lvm_device: /dev/sda

# Data disks
default_system_mount_data_disks: false
default_system_mount_data_disks_filesystem: xfs
default_system_mount_data_disk_mount_options: noatime
default_system_mount_data_disk_mount_paths: ['/mnt/data']


# User parameters
default_system_create_account: false
default_system_create_account_username: vmware
default_system_create_account_password: vmware
#default_system_create_account_key_file: ~/.ssh/id_rsa.pub